### PR TITLE
readme-tw-caldav.md: clarify status property mapping

### PR DESCRIPTION
**Pull request by bjornfor**
# Description

CalDAV objects have a `COMPLETED` property, but what is discussed here is the `STATUS` property, with the value `COMPLETED`, so let's update the doc and be precise by prefixing the values with `STATUS:`.

## Type of change

[x] Small documentation update.

# How Has This Been Tested?

No testing, just edited a few lines in a readme.

### CODE REVIEW

**Comment by bergercookie** [comment]
I'm not sure this is right.

This is the structure of a .ics file downloaded from the caldav server

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PYVOBJECT//NONSGML Version 1//EN
X-WR-CALNAME;VALUE=TEXT:thetasks
BEGIN:VTODO
DESCRIPTION:IMPORTED FROM TASKWARRIOR\n\n\n* uuid: 967b9ce0-3ebb-40c4-84a6-
 eef9a52d4ff0
DTSTAMP:20230830T124838Z
STATUS:NEEDS-ACTION
SUMMARY:kalimera
UID:64f9bad7-471a-11ee-a6d5-0fe81ac3857d
END:VTODO
BEGIN:VTODO
CATEGORIES:buy
DESCRIPTION:IMPORTED FROM TASKWARRIOR\n\n\n* uuid: acb634c6-11d5-444f-b509-
 c4bae81800f7
DTSTAMP:20230830T124838Z
STATUS:COMPLETED
SUMMARY:Hey you
UID:64f9bad8-471a-11ee-a6d5-0fe81ac3857d
END:VTODO
BEGIN:VTODO
DESCRIPTION:IMPORTED FROM TASKWARRIOR\n\n\n* uuid: d44f39a6-c8ac-45a9-8b39-
 602e3e241456
DTSTAMP:20230830T125307Z
PRIORITY:1
STATUS:NEEDS-ACTION
SUMMARY:kalispera
UID:0529e864-471b-11ee-a6d5-0fe81ac3857d
END:VTODO
END:VCALENDAR
```

The current mapping described in the readme does make sense to me, there's a property called `STATUS` and one of its values is the `COMPLETED`.

Same for other properties such as `SUMMARY` and `PRIORITY`

**Comment by bjornfor** [comment]
> I'm not sure this is right.

Ok, I see now, each bullet point of the various STATUS values is grouped under STATUS. I didn't notice until now :smile: 

> Same for other properties such as SUMMARY and PRIORITY

I agree with PRIORITY, but SUMMARY doesn't seem "nested" like PRIORITY and STATUS.

I'll close then.

**Comment by bergercookie** [comment]
> I agree with PRIORITY, but SUMMARY doesn't seem "nested" like PRIORITY and STATUS.

Status or priority are not really nested structures in the ics format. The current documentation tries to convey that for each one of the said tw statuses for example, there's a corresponding caldav `STATUS`. Same for priority. For description <> SUMMARY on the other hand, the conversion is 1-1, hence there is no nesting in the current documentation

**Comment by bjornfor** [comment]
Ok. Sorry for the noise :sweat_smile:

**Pull request closed without merging**
